### PR TITLE
NERDTreeFind takes an optional filename argument

### PR DESCRIPTION
**Pull request by Arrowbox**
NERDTreeFind will default to the filename of the current buffer.
If the current buffer is a NERDTree buffer then the command will
reveal the file in the current tree instead of the primary one.

Allowing for an argument makes it easier for other plugins and user
functions to reveal a file in the NERDTree. I am using it with vim-vinegar
to reveal current file and not change the root directory of the NERDTree.

### CODE REVIEW

**Comment by PhilRunninger** [comment]
@Arrowbox, I like this change. Can you resolve the conflicts in it, and update the doc file with the new functionality?

Thanks for the contribution.

**Comment by PhilRunninger** [comment]
@Arrowbox, are you still interested in merging this PR? I think it would be a good addition. It just needs to have some conflict resolution and documentation updates.

@lifecrisis, what do you think of this one? There are a lot of whitespace changes in this because existing code was moved into an `else` block. I don't know if you've seen this trick or not.... To make comparison easier, at the expense of writing comments on lines of code, you can add `?w=1` to the **Files changed** URL, i.e.: https://github.com/scrooloose/nerdtree/pull/419/files?w=1

**Comment by lifecrisis** [comment]
@PhilRunninger, that's a neat trick!

I'll have to look at this one later.  On the surface, things look good.

**Comment by lifecrisis** [comment]
Looks like we can close this one. @PhilRunninger, when you review the other PR that does the same thing, you can close this at your discretion.

**Comment by lifecrisis** [comment]
Hey @PhilRunninger, I noticed that this version of the feature uses `-complete=file` rather than `-complete=directory` like the other PR that does the same thing...

Do you think we should be using `-complete=file`?

**Comment by PhilRunninger** [comment]
@lifecrisis, yes, that looks like the better way to go. I forgot to close this earlier, so I'll do that now.

**Pull request closed without merging**
