### PR TITLE
Added global variables for changing default arrows

### PR DESCRIPTION
**Pull request by PickRelated**
g:NERDTreeDirArrowExpandable
g:NERDTreeDirArrowCollapsible

### CODE REVIEW

**Comment by PickRelated** [comment]
Please don't judge strictly. This is my first contribution. I am open to suggestions and critics.

**Comment by scrooloose** [comment]
Thanks :) I imagine that certain symbols will mess the regexes up and will need to be escaped, but will deal with these if and when the bug reports come in.

**Comment by PickRelated** [comment]
My pleasure. If someone complains - feel free to write to me. My email is in profile. I know how to deal with that. Though it will not bee too beautifull from code point of view.
For now I just tried to figure out what symbols are likely to show up and break the code. I avoided escaping where this could happen.

**Comment by simonsmith** [comment]
I seem to be getting an error when trying to open NerdTree:

```
Error detected while processing /Users/simonsmith/.vim/plugged/nerdtree/syntax/nerdtree.vim:
line   26:
E121: Undefined variable: g:NERDTreeDirArrowCollapsible
E15: Invalid expression: 'syn match NERDTreeClosable #'.g:NERDTreeDirArrowCollapsible.'# containedin=NERDTreeDir,NERDTreeFile'
```

**Comment by PickRelated** [comment]
I got a response from you on my email but I do not see the post. Is the problem still there? I can fix it.

**Comment by simonsmith** [comment]
Apologies, I managed to resolve the issue after posting

**Comment by PickRelated** [comment]
Okay, cool! I thought I have made a mistake of not defining variable but now I see that variable is defined on autoload. I guess relaunching vim after :PluginUpdate did the trick for you.

**Comment by simonsmith** [comment]
Exactly yeah, I neglected to relaunch Vim :)

**Pull request merged**
