### PR TITLE
Read-only files opening fix

### PR DESCRIPTION
**Pull request by mike-zueff**
Hello @scrooloose,

Within this pull request I propose the fix in order to allow read-only files to be opened as well as regular files.

### CODE REVIEW

**Comment by PhilRunninger** [comment]
👍

**Comment by rmk135** [comment]
👍

**Comment by mrbish** [comment]
:+1

**Comment by andyfuse** [comment]
:like:

**Comment by andyfuse** [comment]
:+1:

**Comment by silvester747** [comment]
I would really want this fix to go in asap. Currently NerdTree is not usable for me, as my scm makes all files read-only...

**Comment by bearlin** [comment]
Rollback below change will also fix this issue, thanks for @mike-zueff's patch just fix it very well:
https://github.com/scrooloose/nerdtree/commit/dfb91117860a33ae911646223d37ffd28907ac21

**Comment by william-mcmillian** [comment]
This is great!!!

**Comment by mkoskar** [comment]
Looking at https://github.com/scrooloose/nerdtree/commit/dfb91117860a33ae911646223d37ffd28907ac21#diff-f094542718c161e8482e397da4e1f499L378 there is no need to introduce `exec` there.

Instead of

```
exec 'let line = substitute (line, " \['.g:NERDTreeGlyphReadOnly.'\]", "","")'
```

just do

```
let line = substitute (line, ' \['.g:NERDTreeGlyphReadOnly.'\]', "","")
```

@mike-zueff would you mind updating your PR? Thanks ;)

**Comment by scrooloose** [comment]
Merged, thanks for the fix!

**Comment by mkoskar** [comment]
@scrooloose Maybe I'm missing something but is that `exec` really necessary there?

**Comment by scrooloose** [comment]
@mkoskar - good point.

**Pull request merged**
