### PR TITLE
Like m-c did before, create parent directories if needed on m-m.

### LINKED ISSUE #360: Create parent directories as needed when moving.
Recently support for creating missing intermediate directories when creating or copying nodes has been added to NERDTree.  However it appears that moving nodes hasn't been invited to the party.

It would be nice if intermediate directories could be created when moving as well.

### PR DESCRIPTION
**Pull request by PhilRunninger**
Fixes #360 and #679.

### CODE REVIEW

**Comment by ilaipi** [comment]
WoW! I like this! Hope to be merged soon.

**Comment by lifecrisis** [comment]
Will review shortly...

**Comment by lifecrisis** [comment]
Tested on Windows 10 and on Ubuntu 16.04.  Everything looks good. Merging...

**Comment by ilaipi** [comment]
Tested on Mac, works well, thanks!

**Pull request merged**
