### PR TITLE
echo a message to alert the user when change tree root using bookmarks or press 'C'(when  g:NERDTreeChDirMode==#2)

### PR DESCRIPTION
**Pull request by skyblueee**
when g:NERDTreeChDirMode==#2 and
1. :BookmarkOpen <bm> OR press 'o' on bookmarks
2. press 'C' to change tree root to the selected dir
make cwd autochange and give hints to users( just as the same with u/U)

### CODE REVIEW

**Comment by lifecrisis** [comment]
I can't replicate the bugs that your pull request purports to fix.  The `NERDTree.changeRoot(node)` function always performs a check of the `g:NERDTreeChDirMode` option and behaves accordingly.  Thus, your changes in `ui_glue.vim` are redundant... they are also examples of code duplication that should be avoided (i.e., both of those functions eventually call `changeRoot()`).

However, the change you made in `nerdtree.vim` is valid. It calls a better function to change the directory that also echoes a message to alert the user.  I like this change and would like to include it.

**Comment by skyblueee** [comment]
Oh, you are right. I'm so sorry for my carelessness and thanks for your reply.

I tested it again to make sure you are right. And now the problem only in nerdtree.vim. And of course it's not called a 'fixing bug', it just make the plugin more friendly.

I have commit it again. :-)

**Comment by lifecrisis** [comment]
Thanks for the prompt reply!

Please fix the indentation of your code, and then I'll be satisfied. We'll wait for approval from @PhilRunninger before merging.  Thanks again!

**Comment by skyblueee** [comment]
Because of my 'noexpandtab' setting, I didn't notice this problem before. 
Have fixed it right now.

**Comment by skyblueee** [comment]
I think it's OK now. And now what should I do? Just wait for a merge?
Actually, I am new in github and wondering what to do at the Deploy step, which is mentioned in https://guides.github.com/introduction/flow/
@lifecrisis @PhilRunninger

**Comment by PhilRunninger** [comment]
The Deploy stage is where someone would check out your branch and make sure NERDTree still works properly. This ensures you've included everything in your commits. Once past that phase, the pull request would be merged into production.

**Comment by lifecrisis** [comment]
Thanks, @PhilRunninger, I'll review one more time and merge tomorrow.

**Comment by skyblueee** [comment]
Thank you both. I find a can click the "close and comment" button now, should I do it now?

Another question, it seems that I have found other things need to be changed and to open a new pull request.
What should I do? Wait for the merge, sync my fork, change, commit, and then open a new pull request? Or just change my fork, commit and open a pull request before this one is closed and merged?

**Comment by lifecrisis** [comment]
At this point you don't have to do anything.  I'll merge the pull request, and the work will be done.

Generally, a new pull request would require a new branch to be created in your fork.  You would then make commits to this branch and open a pull request to have your branch merged into the `master` branch in this repository.  After merging, you can then delete your branch.

Sounds like you need to brush up on your Git skills.  I recommend **Pro Git** by Scott Chacon. It's a free online book.

**Comment by skyblueee** [comment]
@lifecrisis Thanks for your advice very very much! During the past 20+ days I have read over Progit2, and it is very helpful. Now I have corrected the commit history of my fork repo. Thanks again.

**Pull request merged**
