### PR TITLE
Add a 'NERDTreeToggleHere' command

### PR DESCRIPTION
**Pull request by mmequignon**
Targets the current file with the toggle functionnality.

### CODE REVIEW

**Comment by lifecrisis** [comment]
This is a nice idea, but your commit doesn't really contribute to a core feature of the NERDTree.  This type of customization could just as easily have been placed in your `vimrc` file.  Thanks for the effort, but I'll have to motion that this PR be closed.

I'll wait on my colleague @PhilRunninger to weigh in before closing.

**Comment by mmequignon** [comment]
Yes, you're right.
But I find that implementing this "feature" in the .vimrc is not that easy.
I tried to use the NERDTreeToggle optionnal path dynamically. (something like `:NERDTreeToggle expand('%:p')`) but it didn't worked.
I tried to implement the code of my commit in my .virmrc, but I didn't succeeded either.
Maybe it would be interesting to explain in the README how to expand default NERDTree behaviours ?

**Comment by lifecrisis** [comment]
The reason your command didn't work is because you can't pass an expression as an argument to the `:NERDTreeToggle` ex command.

You need to use the `:execute` command to make it work. See the snippet below...

```viml
:execute 'NERDTreeToggle ' . expand('%:p')
```

That line will function as you expect.

**Comment by lifecrisis** [comment]
It is worth noting that `:NERDTreeToggle` does *not* obey an argument when a NERDTree already exists for the current tab.  It only uses its argument on the first invocation. This might be considered a bug by some. But it can easily be worked around for now.

**Comment by lifecrisis** [comment]
As a final note, you could modify your function like so to include it within your `vimrc` file:

```viml
function! s:ToggleTabHere()
    if g:NERDTree.IsOpen()
        call g:NERDTree.Close()
    else
        NERDTreeFind
    endif
endfunction
```

Then, just create a map or command as you wish for your personal use.

**Comment by mmequignon** [comment]
Thank you for your help.
I close the pr.

**Comment by PhilRunninger** [comment]
@mmequignon , here's another, perhaps simpler, option for you. Try mapping this expression to a key in your .vimrc.
```
nnoremap <silent><expr> <leader>f g:NERDTree.IsOpen() ? ":NERDTreeClose\<CR>" : ":NERDTreeFind\<CR>"
```

**Comment by mmequignon** [comment]
Ternary operator, yes.
Thank you !

**Pull request closed without merging**
