### PR TITLE
Fix #520 E716: Key not present in Dictionary: setShowHidden

### LINKED ISSUE #520: Error in NERDTreeFind after changing directory
I do the following:

1. :cd /home/user/somepath
2. Open a file under /home/user/somepath
3. :NERDTreeFind
4. :cd /home/user/otherpath
5. Open a file under /home/user/otherpath
6. :NERDTreeFind

and I get this error:

```
Error detected while processing function <SNR>40_findAndRevealPath:
line   33:
E716: Key not present in Dictionary: setShowHidden 
```

What I am trying here is to switch projects

### PR DESCRIPTION
**Pull request by brookhong**

### CODE REVIEW

**Comment by brookhong** [comment]
Here it is the pull request that you're commenting.

Only those with write access to this repository can merge pull requests.

**Comment by osdiab** [comment]
Is this being merged? kinda annoying error

**Comment by normenmueller** [comment]
Please merge and publish such that Vundle can grab it in next update.

**Comment by balaclark** [comment]
Any update on this? It is quite an annoying bug.

**Comment by scrooloose** [comment]
Merged. Apologies for the delay.

**Pull request merged**
