### PR TITLE
Add menu option to display file/directory properties.

### PR DESCRIPTION
**Pull request by PhilRunninger**
I added a new menu item to the m command, which echos the current node's size and last modified date. As stated in :h getfsize, directories report a size of 0.

Tested on Windows 7, vim  7.4.

### CODE REVIEW

**Comment by scrooloose** [comment]
Hey guys (@apbarrero  again :)) I have merged in #502 which is similar to both of the PRs mentioned here.

This implementation works on windows however....

There are 2 ways to go (AFAICS):

1. Replace the current `ls -ld` implementation with this.
2. Call the `ls -ld` implementation for linux/mac and this implementation for windows.

@apbarrero, @JESii, @PhilRunninger - any preferences/thoughts?

**Comment by PhilRunninger** [comment]
I like the additional info that ls -ld gives on the Mac/Unix client, so my preference is to go with the 2nd option you mentioned.

**Comment by apbarrero** [comment]
:+1: for the `ls -ld` on Mac/Unix

**Comment by PhilRunninger** [comment]
I changed my code to mimic the `ls` command in #376. It uses the Windows command `DIR /Q` to list, for example: 
```
11/12/2015 04:23 PM             4,551 BUILTIN\Administrators README.markdown
```
It's ready for merging.

**Comment by scrooloose** [comment]
Looks good to me - cheers :)

**Pull request merged**
