### PR TITLE
Update NERDTreeOpenable and NERDTreeClosable color

### PR DESCRIPTION
**Pull request by Leeiio**
It is more comfortable

### CODE REVIEW

**Comment by PhilRunninger** [comment]
I don't see anything in the history to indicate the syntax had changed. Regardless, I like the change submitted by @Leeiio .
image

**Comment by svanharmelen** [comment]
@PhilRunninger can we revert this? I really don't agree that this should be more comfortable. Having it be exactly the same color as the dir names make it less clear to my eyes...

**Comment by Leeiio** [comment]
@svanharmelen Maybe you can change the arrow color like this put in your .vimrc right now:
hi NERDTreeOpenable cterm=NONE ctermbg=yellow ctermfg=black guifg=#000000 guibg=NONE
hi NERDTreeClosable cterm=NONE ctermbg=yellow ctermfg=black guifg=#000000 guibg=NONE

I change the arrow color because the #409 metioned.

**Comment by svanharmelen** [comment]
Check... Thanks for the info.

**Pull request merged**
